export const DEV_MODE = true;
export const toastOptions = { duration: 4000, position: "top-center" };
export const initialZoomLvl = 8;
export const animationDuration = 2;
export const navItems = ["Home", "About", "Contacts"];
export const sideBarItems = [...navItems, "Sign In", "Sign Up"];
export const cityOptions = ["london", "delhi", "new york"];
export const typeOptions = ["buy", "rent"];
export const propertyOptions = ["apartment", "house", "condo", "land"];
